# Generated by Django 3.1.1 on 2020-09-20 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('studentenroll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stucourses',
            name='Courses',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentenroll.course'),
        ),
        migrations.AlterField(
            model_name='stucourses',
            name='Student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
